name: link2task
description: Link to task application by Abrams.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_local_notifications: ^0.8.4+2
  fluttertoast: ^4.0.0
  google_fonts: ^1.1.0
  flare_flutter: ^1.5.0
  oktoast: ^2.1.8
  flushbar: ^1.5.0
  intro_slider: ^2.3.1
  percent_indicator: "^2.1.1"
  flutter_country_picker: ^0.1.6
  table_calendar: ^2.2.3
  dash_chat: ^1.1.5
  calendar_views: ^0.5.2
  firebase_messaging: ^6.0.16
  flutter_launcher_icons: "^0.7.3"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - assets/spinner.flr
    - assets/facebook.png
    - assets/google.png
    - assets/linkedin.png
    - assets/twitter.png
    - assets/chat_demo.png